server:
  port: 8080
spring:
  application:
    name: SERVICE-1
  datasource:
    url: jdbc:h2:~/service-1
    driver-class-name: org.h2.Driver
    username:
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

